//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacminMusavir.IseCikisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", ConfigurationName="IseCikisService.WS_SgkIstenCikis")]
    public interface WS_SgkIstenCikis {
        
        // CODEGEN: Parameter 'istenCikisDonemVeGunSayisiBulReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisDonemVeGunSayisiBul", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="istenCikisDonemVeGunSayisiBulReturn")]
        TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulResponse istenCikisDonemVeGunSayisiBul(TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisDonemVeGunSayisiBul", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulResponse> istenCikisDonemVeGunSayisiBulAsync(TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest request);
        
        // CODEGEN: Parameter 'istenCikisKaydetReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisKaydet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="istenCikisKaydetReturn")]
        TacminMusavir.IseCikisService.istenCikisKaydetResponse istenCikisKaydet(TacminMusavir.IseCikisService.istenCikisKaydetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisKaydet", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisKaydetResponse> istenCikisKaydetAsync(TacminMusavir.IseCikisService.istenCikisKaydetRequest request);
        
        // CODEGEN: Parameter 'istenCikisPdfDokumReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisPdfDokum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="istenCikisPdfDokumReturn")]
        TacminMusavir.IseCikisService.istenCikisPdfDokumResponse istenCikisPdfDokum(TacminMusavir.IseCikisService.istenCikisPdfDokumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="istenCikisPdfDokum", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisPdfDokumResponse> istenCikisPdfDokumAsync(TacminMusavir.IseCikisService.istenCikisPdfDokumRequest request);
        
        // CODEGEN: Parameter 'tckimlikNoileistenCikisSorgulaReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoileistenCikisSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tckimlikNoileistenCikisSorgulaReturn")]
        TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaResponse tckimlikNoileistenCikisSorgula(TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoileistenCikisSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaResponse> tckimlikNoileistenCikisSorgulaAsync(TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest request);
        
        // CODEGEN: Parameter 'tckimlikNoTarihileistenCikisSorgulaReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoTarihileistenCikisSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tckimlikNoTarihileistenCikisSorgulaReturn")]
        TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaResponse tckimlikNoTarihileistenCikisSorgula(TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoTarihileistenCikisSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaResponse> tckimlikNoTarihileistenCikisSorgulaAsync(TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class kullaniciBilgileri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string isyeriKoduField;
        
        private string sistemSifreField;
        
        private string isyeriSifreField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("kullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isyeriKodu {
            get {
                return this.isyeriKoduField;
            }
            set {
                this.isyeriKoduField = value;
                this.RaisePropertyChanged("isyeriKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sistemSifre {
            get {
                return this.sistemSifreField;
            }
            set {
                this.sistemSifreField = value;
                this.RaisePropertyChanged("sistemSifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string isyeriSifre {
            get {
                return this.isyeriSifreField;
            }
            set {
                this.isyeriSifreField = value;
                this.RaisePropertyChanged("isyeriSifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isyeriSicil {
            get {
                return this.isyeriSicilField;
            }
            set {
                this.isyeriSicilField = value;
                this.RaisePropertyChanged("isyeriSicil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class tcKimlikTarihtenIstenCikisSorParametre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        private string istenCikisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
                this.RaisePropertyChanged("kullaniciBilgileri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string istenCikisTarihi {
            get {
                return this.istenCikisTarihiField;
            }
            set {
                this.istenCikisTarihiField = value;
                this.RaisePropertyChanged("istenCikisTarihi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sgkIstenCikisKaydi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tckimlikNoField;
        
        private long sicilnoField;
        
        private string cikisTarihiField;
        
        private string islemTarihiField;
        
        private double idariParaCezasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
                this.RaisePropertyChanged("tckimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sicilno {
            get {
                return this.sicilnoField;
            }
            set {
                this.sicilnoField = value;
                this.RaisePropertyChanged("sicilno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cikisTarihi {
            get {
                return this.cikisTarihiField;
            }
            set {
                this.cikisTarihiField = value;
                this.RaisePropertyChanged("cikisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
                this.RaisePropertyChanged("islemTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double idariParaCezasi {
            get {
                return this.idariParaCezasiField;
            }
            set {
                this.idariParaCezasiField = value;
                this.RaisePropertyChanged("idariParaCezasi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class istenCikisListesi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hatakoduField;
        
        private string hataAciklamaField;
        
        private sgkIstenCikisKaydi[] istenCikisKayitlariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hatakodu {
            get {
                return this.hatakoduField;
            }
            set {
                this.hatakoduField = value;
                this.RaisePropertyChanged("hatakodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
                this.RaisePropertyChanged("hataAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("istenCikisKayitlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sgkIstenCikisKaydi[] istenCikisKayitlari {
            get {
                return this.istenCikisKayitlariField;
            }
            set {
                this.istenCikisKayitlariField = value;
                this.RaisePropertyChanged("istenCikisKayitlari");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class tcKimliktenIstenCikisSorParametre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
                this.RaisePropertyChanged("kullaniciBilgileri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class pdfDokumSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hataAciklamaField;
        
        private int hatakoduField;
        
        private byte[] pdfByteArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
                this.RaisePropertyChanged("hataAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int hatakodu {
            get {
                return this.hatakoduField;
            }
            set {
                this.hatakoduField = value;
                this.RaisePropertyChanged("hatakodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] pdfByteArray {
            get {
                return this.pdfByteArrayField;
            }
            set {
                this.pdfByteArrayField = value;
                this.RaisePropertyChanged("pdfByteArray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sigortaliIstenCikisSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long islemSonucuField;
        
        private string islemAciklamasiField;
        
        private long tcKimlikNoField;
        
        private string sicilnoField;
        
        private string adSoyadField;
        
        private long referansKoduField;
        
        private string istenCikisTarihiField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long islemSonucu {
            get {
                return this.islemSonucuField;
            }
            set {
                this.islemSonucuField = value;
                this.RaisePropertyChanged("islemSonucu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string islemAciklamasi {
            get {
                return this.islemAciklamasiField;
            }
            set {
                this.islemAciklamasiField = value;
                this.RaisePropertyChanged("islemAciklamasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sicilno {
            get {
                return this.sicilnoField;
            }
            set {
                this.sicilnoField = value;
                this.RaisePropertyChanged("sicilno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string adSoyad {
            get {
                return this.adSoyadField;
            }
            set {
                this.adSoyadField = value;
                this.RaisePropertyChanged("adSoyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long referansKodu {
            get {
                return this.referansKoduField;
            }
            set {
                this.referansKoduField = value;
                this.RaisePropertyChanged("referansKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string istenCikisTarihi {
            get {
                return this.istenCikisTarihiField;
            }
            set {
                this.istenCikisTarihiField = value;
                this.RaisePropertyChanged("istenCikisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string isyeriSicil {
            get {
                return this.isyeriSicilField;
            }
            set {
                this.isyeriSicilField = value;
                this.RaisePropertyChanged("isyeriSicil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sigortaliIstenCikisIslemSonuclari : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hataKoduField;
        
        private string hataAciklamasiField;
        
        private sigortaliIstenCikisSonuc[] sigortaliIstenCikisSonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklamasi {
            get {
                return this.hataAciklamasiField;
            }
            set {
                this.hataAciklamasiField = value;
                this.RaisePropertyChanged("hataAciklamasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIstenCikisSonuc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sigortaliIstenCikisSonuc[] sigortaliIstenCikisSonuc {
            get {
                return this.sigortaliIstenCikisSonucField;
            }
            set {
                this.sigortaliIstenCikisSonucField = value;
                this.RaisePropertyChanged("sigortaliIstenCikisSonuc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class oncekiDonem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short belgeturuField;
        
        private double hakedilenucretField;
        
        private double primikramiyeField;
        
        private short eksikgunsayisiField;
        
        private short eksikgunnedeniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short belgeturu {
            get {
                return this.belgeturuField;
            }
            set {
                this.belgeturuField = value;
                this.RaisePropertyChanged("belgeturu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double hakedilenucret {
            get {
                return this.hakedilenucretField;
            }
            set {
                this.hakedilenucretField = value;
                this.RaisePropertyChanged("hakedilenucret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double primikramiye {
            get {
                return this.primikramiyeField;
            }
            set {
                this.primikramiyeField = value;
                this.RaisePropertyChanged("primikramiye");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short eksikgunsayisi {
            get {
                return this.eksikgunsayisiField;
            }
            set {
                this.eksikgunsayisiField = value;
                this.RaisePropertyChanged("eksikgunsayisi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short eksikgunnedeni {
            get {
                return this.eksikgunnedeniField;
            }
            set {
                this.eksikgunnedeniField = value;
                this.RaisePropertyChanged("eksikgunnedeni");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class bulundugumuzDonem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short belgeturuField;
        
        private double hakedilenucretField;
        
        private double primikramiyeField;
        
        private short eksikgunsayisiField;
        
        private short eksikgunnedeniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short belgeturu {
            get {
                return this.belgeturuField;
            }
            set {
                this.belgeturuField = value;
                this.RaisePropertyChanged("belgeturu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double hakedilenucret {
            get {
                return this.hakedilenucretField;
            }
            set {
                this.hakedilenucretField = value;
                this.RaisePropertyChanged("hakedilenucret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double primikramiye {
            get {
                return this.primikramiyeField;
            }
            set {
                this.primikramiyeField = value;
                this.RaisePropertyChanged("primikramiye");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short eksikgunsayisi {
            get {
                return this.eksikgunsayisiField;
            }
            set {
                this.eksikgunsayisiField = value;
                this.RaisePropertyChanged("eksikgunsayisi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short eksikgunnedeni {
            get {
                return this.eksikgunnedeniField;
            }
            set {
                this.eksikgunnedeniField = value;
                this.RaisePropertyChanged("eksikgunnedeni");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sigortaliIstenCikis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tckimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string istenCikisTarihiField;
        
        private string istenCikisNedeniField;
        
        private string meslekkoduField;
        
        private string csgbiskoluField;
        
        private bulundugumuzDonem bulundugumuzDonemField;
        
        private oncekiDonem oncekiDonemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
                this.RaisePropertyChanged("tckimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
                this.RaisePropertyChanged("ad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
                this.RaisePropertyChanged("soyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string istenCikisTarihi {
            get {
                return this.istenCikisTarihiField;
            }
            set {
                this.istenCikisTarihiField = value;
                this.RaisePropertyChanged("istenCikisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string istenCikisNedeni {
            get {
                return this.istenCikisNedeniField;
            }
            set {
                this.istenCikisNedeniField = value;
                this.RaisePropertyChanged("istenCikisNedeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string meslekkodu {
            get {
                return this.meslekkoduField;
            }
            set {
                this.meslekkoduField = value;
                this.RaisePropertyChanged("meslekkodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string csgbiskolu {
            get {
                return this.csgbiskoluField;
            }
            set {
                this.csgbiskoluField = value;
                this.RaisePropertyChanged("csgbiskolu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bulundugumuzDonem bulundugumuzDonem {
            get {
                return this.bulundugumuzDonemField;
            }
            set {
                this.bulundugumuzDonemField = value;
                this.RaisePropertyChanged("bulundugumuzDonem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public oncekiDonem oncekiDonem {
            get {
                return this.oncekiDonemField;
            }
            set {
                this.oncekiDonemField = value;
                this.RaisePropertyChanged("oncekiDonem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class sgk4AIstenCikisParametre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private sigortaliIstenCikis[] sigortaliIstenCikisListesiField;
        
        private string nakilGidecegiIsyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
                this.RaisePropertyChanged("kullaniciBilgileri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIstenCikisListesi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sigortaliIstenCikis[] sigortaliIstenCikisListesi {
            get {
                return this.sigortaliIstenCikisListesiField;
            }
            set {
                this.sigortaliIstenCikisListesiField = value;
                this.RaisePropertyChanged("sigortaliIstenCikisListesi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nakilGidecegiIsyeriSicil {
            get {
                return this.nakilGidecegiIsyeriSicilField;
            }
            set {
                this.nakilGidecegiIsyeriSicilField = value;
                this.RaisePropertyChanged("nakilGidecegiIsyeriSicil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr")]
    public partial class istenCikisDonemBilgileri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tckimlikNoField;
        
        private int islemSonucuField;
        
        private string islemSonucAciklamasiField;
        
        private string istenCikisTarihiField;
        
        private string iseGirisTarihiField;
        
        private string bulundugumuzDonemBaslangicTarihiField;
        
        private string bulundugumuzDonemBitisTarihiField;
        
        private int bulundugumuzDonemGunSayisiField;
        
        private string oncekiDonemBaslangicTarihiField;
        
        private string oncekiDonemBitisTarihiField;
        
        private int oncekiDonemGunSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
                this.RaisePropertyChanged("tckimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int islemSonucu {
            get {
                return this.islemSonucuField;
            }
            set {
                this.islemSonucuField = value;
                this.RaisePropertyChanged("islemSonucu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string islemSonucAciklamasi {
            get {
                return this.islemSonucAciklamasiField;
            }
            set {
                this.islemSonucAciklamasiField = value;
                this.RaisePropertyChanged("islemSonucAciklamasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string istenCikisTarihi {
            get {
                return this.istenCikisTarihiField;
            }
            set {
                this.istenCikisTarihiField = value;
                this.RaisePropertyChanged("istenCikisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string iseGirisTarihi {
            get {
                return this.iseGirisTarihiField;
            }
            set {
                this.iseGirisTarihiField = value;
                this.RaisePropertyChanged("iseGirisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string bulundugumuzDonemBaslangicTarihi {
            get {
                return this.bulundugumuzDonemBaslangicTarihiField;
            }
            set {
                this.bulundugumuzDonemBaslangicTarihiField = value;
                this.RaisePropertyChanged("bulundugumuzDonemBaslangicTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string bulundugumuzDonemBitisTarihi {
            get {
                return this.bulundugumuzDonemBitisTarihiField;
            }
            set {
                this.bulundugumuzDonemBitisTarihiField = value;
                this.RaisePropertyChanged("bulundugumuzDonemBitisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int bulundugumuzDonemGunSayisi {
            get {
                return this.bulundugumuzDonemGunSayisiField;
            }
            set {
                this.bulundugumuzDonemGunSayisiField = value;
                this.RaisePropertyChanged("bulundugumuzDonemGunSayisi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string oncekiDonemBaslangicTarihi {
            get {
                return this.oncekiDonemBaslangicTarihiField;
            }
            set {
                this.oncekiDonemBaslangicTarihiField = value;
                this.RaisePropertyChanged("oncekiDonemBaslangicTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string oncekiDonemBitisTarihi {
            get {
                return this.oncekiDonemBitisTarihiField;
            }
            set {
                this.oncekiDonemBitisTarihiField = value;
                this.RaisePropertyChanged("oncekiDonemBitisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int oncekiDonemGunSayisi {
            get {
                return this.oncekiDonemGunSayisiField;
            }
            set {
                this.oncekiDonemGunSayisiField = value;
                this.RaisePropertyChanged("oncekiDonemGunSayisi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisDonemVeGunSayisiBul", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisDonemVeGunSayisiBulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.kullaniciBilgileri kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tckimlikno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string istenCikisTarihi;
        
        public istenCikisDonemVeGunSayisiBulRequest() {
        }
        
        public istenCikisDonemVeGunSayisiBulRequest(TacminMusavir.IseCikisService.kullaniciBilgileri kullanici, long tckimlikno, string istenCikisTarihi) {
            this.kullanici = kullanici;
            this.tckimlikno = tckimlikno;
            this.istenCikisTarihi = istenCikisTarihi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisDonemVeGunSayisiBulResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisDonemVeGunSayisiBulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.istenCikisDonemBilgileri istenCikisDonemVeGunSayisiBulReturn;
        
        public istenCikisDonemVeGunSayisiBulResponse() {
        }
        
        public istenCikisDonemVeGunSayisiBulResponse(TacminMusavir.IseCikisService.istenCikisDonemBilgileri istenCikisDonemVeGunSayisiBulReturn) {
            this.istenCikisDonemVeGunSayisiBulReturn = istenCikisDonemVeGunSayisiBulReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisKaydet", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisKaydetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.sgk4AIstenCikisParametre sgk4aIstenCikisParametre;
        
        public istenCikisKaydetRequest() {
        }
        
        public istenCikisKaydetRequest(TacminMusavir.IseCikisService.sgk4AIstenCikisParametre sgk4aIstenCikisParametre) {
            this.sgk4aIstenCikisParametre = sgk4aIstenCikisParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisKaydetResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisKaydetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.sigortaliIstenCikisIslemSonuclari istenCikisKaydetReturn;
        
        public istenCikisKaydetResponse() {
        }
        
        public istenCikisKaydetResponse(TacminMusavir.IseCikisService.sigortaliIstenCikisIslemSonuclari istenCikisKaydetReturn) {
            this.istenCikisKaydetReturn = istenCikisKaydetReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisPdfDokum", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisPdfDokumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.kullaniciBilgileri kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long referansKodu;
        
        public istenCikisPdfDokumRequest() {
        }
        
        public istenCikisPdfDokumRequest(TacminMusavir.IseCikisService.kullaniciBilgileri kullanici, long referansKodu) {
            this.kullanici = kullanici;
            this.referansKodu = referansKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istenCikisPdfDokumResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class istenCikisPdfDokumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.pdfDokumSonuc istenCikisPdfDokumReturn;
        
        public istenCikisPdfDokumResponse() {
        }
        
        public istenCikisPdfDokumResponse(TacminMusavir.IseCikisService.pdfDokumSonuc istenCikisPdfDokumReturn) {
            this.istenCikisPdfDokumReturn = istenCikisPdfDokumReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileistenCikisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileistenCikisSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre;
        
        public tckimlikNoileistenCikisSorgulaRequest() {
        }
        
        public tckimlikNoileistenCikisSorgulaRequest(TacminMusavir.IseCikisService.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre) {
            this.tcKimliktenIstenCikisSorParametre = tcKimliktenIstenCikisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileistenCikisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileistenCikisSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.istenCikisListesi tckimlikNoileistenCikisSorgulaReturn;
        
        public tckimlikNoileistenCikisSorgulaResponse() {
        }
        
        public tckimlikNoileistenCikisSorgulaResponse(TacminMusavir.IseCikisService.istenCikisListesi tckimlikNoileistenCikisSorgulaReturn) {
            this.tckimlikNoileistenCikisSorgulaReturn = tckimlikNoileistenCikisSorgulaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileistenCikisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileistenCikisSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre;
        
        public tckimlikNoTarihileistenCikisSorgulaRequest() {
        }
        
        public tckimlikNoTarihileistenCikisSorgulaRequest(TacminMusavir.IseCikisService.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre) {
            this.tcKimlikTarihtenIstenCikisSorParametre = tcKimlikTarihtenIstenCikisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileistenCikisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileistenCikisSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.istencikis.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TacminMusavir.IseCikisService.istenCikisListesi tckimlikNoTarihileistenCikisSorgulaReturn;
        
        public tckimlikNoTarihileistenCikisSorgulaResponse() {
        }
        
        public tckimlikNoTarihileistenCikisSorgulaResponse(TacminMusavir.IseCikisService.istenCikisListesi tckimlikNoTarihileistenCikisSorgulaReturn) {
            this.tckimlikNoTarihileistenCikisSorgulaReturn = tckimlikNoTarihileistenCikisSorgulaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SgkIstenCikisChannel : TacminMusavir.IseCikisService.WS_SgkIstenCikis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SgkIstenCikisClient : System.ServiceModel.ClientBase<TacminMusavir.IseCikisService.WS_SgkIstenCikis>, TacminMusavir.IseCikisService.WS_SgkIstenCikis {
        
        public WS_SgkIstenCikisClient() {
        }
        
        public WS_SgkIstenCikisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SgkIstenCikisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SgkIstenCikisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SgkIstenCikisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulResponse TacminMusavir.IseCikisService.WS_SgkIstenCikis.istenCikisDonemVeGunSayisiBul(TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest request) {
            return base.Channel.istenCikisDonemVeGunSayisiBul(request);
        }
        
        public TacminMusavir.IseCikisService.istenCikisDonemBilgileri istenCikisDonemVeGunSayisiBul(TacminMusavir.IseCikisService.kullaniciBilgileri kullanici, long tckimlikno, string istenCikisTarihi) {
            TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest inValue = new TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest();
            inValue.kullanici = kullanici;
            inValue.tckimlikno = tckimlikno;
            inValue.istenCikisTarihi = istenCikisTarihi;
            TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulResponse retVal = ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).istenCikisDonemVeGunSayisiBul(inValue);
            return retVal.istenCikisDonemVeGunSayisiBulReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulResponse> TacminMusavir.IseCikisService.WS_SgkIstenCikis.istenCikisDonemVeGunSayisiBulAsync(TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest request) {
            return base.Channel.istenCikisDonemVeGunSayisiBulAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulResponse> istenCikisDonemVeGunSayisiBulAsync(TacminMusavir.IseCikisService.kullaniciBilgileri kullanici, long tckimlikno, string istenCikisTarihi) {
            TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest inValue = new TacminMusavir.IseCikisService.istenCikisDonemVeGunSayisiBulRequest();
            inValue.kullanici = kullanici;
            inValue.tckimlikno = tckimlikno;
            inValue.istenCikisTarihi = istenCikisTarihi;
            return ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).istenCikisDonemVeGunSayisiBulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.IseCikisService.istenCikisKaydetResponse TacminMusavir.IseCikisService.WS_SgkIstenCikis.istenCikisKaydet(TacminMusavir.IseCikisService.istenCikisKaydetRequest request) {
            return base.Channel.istenCikisKaydet(request);
        }
        
        public TacminMusavir.IseCikisService.sigortaliIstenCikisIslemSonuclari istenCikisKaydet(TacminMusavir.IseCikisService.sgk4AIstenCikisParametre sgk4aIstenCikisParametre) {
            TacminMusavir.IseCikisService.istenCikisKaydetRequest inValue = new TacminMusavir.IseCikisService.istenCikisKaydetRequest();
            inValue.sgk4aIstenCikisParametre = sgk4aIstenCikisParametre;
            TacminMusavir.IseCikisService.istenCikisKaydetResponse retVal = ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).istenCikisKaydet(inValue);
            return retVal.istenCikisKaydetReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisKaydetResponse> TacminMusavir.IseCikisService.WS_SgkIstenCikis.istenCikisKaydetAsync(TacminMusavir.IseCikisService.istenCikisKaydetRequest request) {
            return base.Channel.istenCikisKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisKaydetResponse> istenCikisKaydetAsync(TacminMusavir.IseCikisService.sgk4AIstenCikisParametre sgk4aIstenCikisParametre) {
            TacminMusavir.IseCikisService.istenCikisKaydetRequest inValue = new TacminMusavir.IseCikisService.istenCikisKaydetRequest();
            inValue.sgk4aIstenCikisParametre = sgk4aIstenCikisParametre;
            return ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).istenCikisKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.IseCikisService.istenCikisPdfDokumResponse TacminMusavir.IseCikisService.WS_SgkIstenCikis.istenCikisPdfDokum(TacminMusavir.IseCikisService.istenCikisPdfDokumRequest request) {
            return base.Channel.istenCikisPdfDokum(request);
        }
        
        public TacminMusavir.IseCikisService.pdfDokumSonuc istenCikisPdfDokum(TacminMusavir.IseCikisService.kullaniciBilgileri kullanici, long referansKodu) {
            TacminMusavir.IseCikisService.istenCikisPdfDokumRequest inValue = new TacminMusavir.IseCikisService.istenCikisPdfDokumRequest();
            inValue.kullanici = kullanici;
            inValue.referansKodu = referansKodu;
            TacminMusavir.IseCikisService.istenCikisPdfDokumResponse retVal = ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).istenCikisPdfDokum(inValue);
            return retVal.istenCikisPdfDokumReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisPdfDokumResponse> TacminMusavir.IseCikisService.WS_SgkIstenCikis.istenCikisPdfDokumAsync(TacminMusavir.IseCikisService.istenCikisPdfDokumRequest request) {
            return base.Channel.istenCikisPdfDokumAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.IseCikisService.istenCikisPdfDokumResponse> istenCikisPdfDokumAsync(TacminMusavir.IseCikisService.kullaniciBilgileri kullanici, long referansKodu) {
            TacminMusavir.IseCikisService.istenCikisPdfDokumRequest inValue = new TacminMusavir.IseCikisService.istenCikisPdfDokumRequest();
            inValue.kullanici = kullanici;
            inValue.referansKodu = referansKodu;
            return ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).istenCikisPdfDokumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaResponse TacminMusavir.IseCikisService.WS_SgkIstenCikis.tckimlikNoileistenCikisSorgula(TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest request) {
            return base.Channel.tckimlikNoileistenCikisSorgula(request);
        }
        
        public TacminMusavir.IseCikisService.istenCikisListesi tckimlikNoileistenCikisSorgula(TacminMusavir.IseCikisService.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre) {
            TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest inValue = new TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest();
            inValue.tcKimliktenIstenCikisSorParametre = tcKimliktenIstenCikisSorParametre;
            TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaResponse retVal = ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).tckimlikNoileistenCikisSorgula(inValue);
            return retVal.tckimlikNoileistenCikisSorgulaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaResponse> TacminMusavir.IseCikisService.WS_SgkIstenCikis.tckimlikNoileistenCikisSorgulaAsync(TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest request) {
            return base.Channel.tckimlikNoileistenCikisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaResponse> tckimlikNoileistenCikisSorgulaAsync(TacminMusavir.IseCikisService.tcKimliktenIstenCikisSorParametre tcKimliktenIstenCikisSorParametre) {
            TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest inValue = new TacminMusavir.IseCikisService.tckimlikNoileistenCikisSorgulaRequest();
            inValue.tcKimliktenIstenCikisSorParametre = tcKimliktenIstenCikisSorParametre;
            return ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).tckimlikNoileistenCikisSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaResponse TacminMusavir.IseCikisService.WS_SgkIstenCikis.tckimlikNoTarihileistenCikisSorgula(TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest request) {
            return base.Channel.tckimlikNoTarihileistenCikisSorgula(request);
        }
        
        public TacminMusavir.IseCikisService.istenCikisListesi tckimlikNoTarihileistenCikisSorgula(TacminMusavir.IseCikisService.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre) {
            TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest inValue = new TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest();
            inValue.tcKimlikTarihtenIstenCikisSorParametre = tcKimlikTarihtenIstenCikisSorParametre;
            TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaResponse retVal = ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).tckimlikNoTarihileistenCikisSorgula(inValue);
            return retVal.tckimlikNoTarihileistenCikisSorgulaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaResponse> TacminMusavir.IseCikisService.WS_SgkIstenCikis.tckimlikNoTarihileistenCikisSorgulaAsync(TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest request) {
            return base.Channel.tckimlikNoTarihileistenCikisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaResponse> tckimlikNoTarihileistenCikisSorgulaAsync(TacminMusavir.IseCikisService.tcKimlikTarihtenIstenCikisSorParametre tcKimlikTarihtenIstenCikisSorParametre) {
            TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest inValue = new TacminMusavir.IseCikisService.tckimlikNoTarihileistenCikisSorgulaRequest();
            inValue.tcKimlikTarihtenIstenCikisSorParametre = tcKimlikTarihtenIstenCikisSorParametre;
            return ((TacminMusavir.IseCikisService.WS_SgkIstenCikis)(this)).tckimlikNoTarihileistenCikisSorgulaAsync(inValue);
        }
    }
}
