//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacminMusavir.GIBBilgiServisi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gbs.nps.tnb.org.tr/", ConfigurationName="GIBBilgiServisi.GIBBilgiServisiSoap")]
    public interface GIBBilgiServisiSoap {
        
        // CODEGEN: Generating message contract since message TuzelSahisMukellefMerkezBilgiSorguRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://gbs.nps.tnb.org.tr/TuzelSahisMukellefMerkezBilgiSorgu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kayit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguResponse TuzelSahisMukellefMerkezBilgiSorgu(TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gbs.nps.tnb.org.tr/TuzelSahisMukellefMerkezBilgiSorgu", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguResponse> TuzelSahisMukellefMerkezBilgiSorguAsync(TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest request);
        
        // CODEGEN: Generating message contract since message GercekSahisMukellefMerkezBilgiSorguRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://gbs.nps.tnb.org.tr/GercekSahisMukellefMerkezBilgiSorgu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kayit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguResponse GercekSahisMukellefMerkezBilgiSorgu(TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gbs.nps.tnb.org.tr/GercekSahisMukellefMerkezBilgiSorgu", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguResponse> GercekSahisMukellefMerkezBilgiSorguAsync(TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest request);
        
        // CODEGEN: Generating message contract since message BaglantiTestiResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://gbs.nps.tnb.org.tr/BaglantiTesti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kayit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TacminMusavir.GIBBilgiServisi.BaglantiTestiResponse BaglantiTesti(TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gbs.nps.tnb.org.tr/BaglantiTesti", ReplyAction="*")]
        System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.BaglantiTestiResponse> BaglantiTestiAsync(TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class BilgiServisHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NPSIslemTipi islemTipiField;
        
        private ProgramAdi programField;
        
        private long nPSBelgeNOField;
        
        private string sifreField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NPSIslemTipi IslemTipi {
            get {
                return this.islemTipiField;
            }
            set {
                this.islemTipiField = value;
                this.RaisePropertyChanged("IslemTipi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ProgramAdi Program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
                this.RaisePropertyChanged("Program");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long NPSBelgeNO {
            get {
                return this.nPSBelgeNOField;
            }
            set {
                this.nPSBelgeNOField = value;
                this.RaisePropertyChanged("NPSBelgeNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("Sifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public enum NPSIslemTipi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        AracSatisi,
        
        /// <remarks/>
        DefterOnayi,
        
        /// <remarks/>
        SendikaUyelik,
        
        /// <remarks/>
        BelgeOnayi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public enum ProgramAdi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        Vezne,
        
        /// <remarks/>
        YazimNet,
        
        /// <remarks/>
        VezneNet,
        
        /// <remarks/>
        TNBOnline,
        
        /// <remarks/>
        NBS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class ServisHata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mesajField;
        
        private string kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mesaj {
            get {
                return this.mesajField;
            }
            set {
                this.mesajField = value;
                this.RaisePropertyChanged("Mesaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("Kod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class ServisHataHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServisHata servisHataField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServisHata ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
                this.RaisePropertyChanged("ServisHata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoterlikKimlik))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public abstract partial class Kayit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private DataRowState kayitDurumuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DataRowState KayitDurumu {
            get {
                return this.kayitDurumuField;
            }
            set {
                this.kayitDurumuField = value;
                this.RaisePropertyChanged("KayitDurumu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public enum DataRowState {
        
        /// <remarks/>
        Detached = 1,
        
        /// <remarks/>
        Unchanged = 2,
        
        /// <remarks/>
        Added = 4,
        
        /// <remarks/>
        Deleted = 8,
        
        /// <remarks/>
        Modified = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class NoterlikKimlik : Kayit {
        
        private string noterlikKoduField;
        
        private long noterTCKNField;
        
        private long imzaYetkiliTCKNField;
        
        private string sertifikaIDField;
        
        private string kullaniciAdiField;
        
        private ProgramAdi programAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoterlikKodu {
            get {
                return this.noterlikKoduField;
            }
            set {
                this.noterlikKoduField = value;
                this.RaisePropertyChanged("NoterlikKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long NoterTCKN {
            get {
                return this.noterTCKNField;
            }
            set {
                this.noterTCKNField = value;
                this.RaisePropertyChanged("NoterTCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ImzaYetkiliTCKN {
            get {
                return this.imzaYetkiliTCKNField;
            }
            set {
                this.imzaYetkiliTCKNField = value;
                this.RaisePropertyChanged("ImzaYetkiliTCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SertifikaID {
            get {
                return this.sertifikaIDField;
            }
            set {
                this.sertifikaIDField = value;
                this.RaisePropertyChanged("SertifikaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ProgramAdi ProgramAdi {
            get {
                return this.programAdiField;
            }
            set {
                this.programAdiField = value;
                this.RaisePropertyChanged("ProgramAdi");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class NoterlikKimlikHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NoterlikKimlik noterlikKimlikField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NoterlikKimlik NoterlikKimlik {
            get {
                return this.noterlikKimlikField;
            }
            set {
                this.noterlikKimlikField = value;
                this.RaisePropertyChanged("NoterlikKimlik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class Meslek : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string meslekAdiField;
        
        private string meslekKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MeslekAdi {
            get {
                return this.meslekAdiField;
            }
            set {
                this.meslekAdiField = value;
                this.RaisePropertyChanged("MeslekAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MeslekKodu {
            get {
                return this.meslekKoduField;
            }
            set {
                this.meslekKoduField = value;
                this.RaisePropertyChanged("MeslekKodu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class Adres : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mahalleSemtField;
        
        private string caddeSokakField;
        
        private string kapiNOField;
        
        private string daireNOField;
        
        private string ilceAdiField;
        
        private string ilKoduField;
        
        private string ilAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MahalleSemt {
            get {
                return this.mahalleSemtField;
            }
            set {
                this.mahalleSemtField = value;
                this.RaisePropertyChanged("MahalleSemt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CaddeSokak {
            get {
                return this.caddeSokakField;
            }
            set {
                this.caddeSokakField = value;
                this.RaisePropertyChanged("CaddeSokak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KapiNO {
            get {
                return this.kapiNOField;
            }
            set {
                this.kapiNOField = value;
                this.RaisePropertyChanged("KapiNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DaireNO {
            get {
                return this.daireNOField;
            }
            set {
                this.daireNOField = value;
                this.RaisePropertyChanged("DaireNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IlceAdi {
            get {
                return this.ilceAdiField;
            }
            set {
                this.ilceAdiField = value;
                this.RaisePropertyChanged("IlceAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IlKodu {
            get {
                return this.ilKoduField;
            }
            set {
                this.ilKoduField = value;
                this.RaisePropertyChanged("IlKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IlAdi {
            get {
                return this.ilAdiField;
            }
            set {
                this.ilAdiField = value;
                this.RaisePropertyChanged("IlAdi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BilgiSorguSonuc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MerkezBilgiSorguSonuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class ServisSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short sonucKodField;
        
        private string sonucAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short SonucKod {
            get {
                return this.sonucKodField;
            }
            set {
                this.sonucKodField = value;
                this.RaisePropertyChanged("SonucKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SonucAciklama {
            get {
                return this.sonucAciklamaField;
            }
            set {
                this.sonucAciklamaField = value;
                this.RaisePropertyChanged("SonucAciklama");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MerkezBilgiSorguSonuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class BilgiSorguSonuc : ServisSonuc {
        
        private long sonucReferansNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long SonucReferansNO {
            get {
                return this.sonucReferansNOField;
            }
            set {
                this.sonucReferansNOField = value;
                this.RaisePropertyChanged("SonucReferansNO");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public partial class MerkezBilgiSorguSonuc : BilgiSorguSonuc {
        
        private string adiField;
        
        private string soyadiField;
        
        private string babaAdiField;
        
        private string vergiDairesiAdiField;
        
        private string vergiDairesiKoduField;
        
        private string vKNField;
        
        private string unvanField;
        
        private Adres isAdresiField;
        
        private Adres ikametgahAdresiField;
        
        private Meslek[] meslekListesiField;
        
        private GIBFaalKodlari faalTerkBilgisiField;
        
        private GIBSirketTurleri sirketTuruField;
        
        private KimlikNOTipi sorguKimlikNOTipiField;
        
        private string sorguKimlikNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("Adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Soyadi {
            get {
                return this.soyadiField;
            }
            set {
                this.soyadiField = value;
                this.RaisePropertyChanged("Soyadi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BabaAdi {
            get {
                return this.babaAdiField;
            }
            set {
                this.babaAdiField = value;
                this.RaisePropertyChanged("BabaAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VergiDairesiAdi {
            get {
                return this.vergiDairesiAdiField;
            }
            set {
                this.vergiDairesiAdiField = value;
                this.RaisePropertyChanged("VergiDairesiAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VergiDairesiKodu {
            get {
                return this.vergiDairesiKoduField;
            }
            set {
                this.vergiDairesiKoduField = value;
                this.RaisePropertyChanged("VergiDairesiKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string VKN {
            get {
                return this.vKNField;
            }
            set {
                this.vKNField = value;
                this.RaisePropertyChanged("VKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Unvan {
            get {
                return this.unvanField;
            }
            set {
                this.unvanField = value;
                this.RaisePropertyChanged("Unvan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Adres IsAdresi {
            get {
                return this.isAdresiField;
            }
            set {
                this.isAdresiField = value;
                this.RaisePropertyChanged("IsAdresi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Adres IkametgahAdresi {
            get {
                return this.ikametgahAdresiField;
            }
            set {
                this.ikametgahAdresiField = value;
                this.RaisePropertyChanged("IkametgahAdresi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public Meslek[] MeslekListesi {
            get {
                return this.meslekListesiField;
            }
            set {
                this.meslekListesiField = value;
                this.RaisePropertyChanged("MeslekListesi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public GIBFaalKodlari FaalTerkBilgisi {
            get {
                return this.faalTerkBilgisiField;
            }
            set {
                this.faalTerkBilgisiField = value;
                this.RaisePropertyChanged("FaalTerkBilgisi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public GIBSirketTurleri SirketTuru {
            get {
                return this.sirketTuruField;
            }
            set {
                this.sirketTuruField = value;
                this.RaisePropertyChanged("SirketTuru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public KimlikNOTipi SorguKimlikNOTipi {
            get {
                return this.sorguKimlikNOTipiField;
            }
            set {
                this.sorguKimlikNOTipiField = value;
                this.RaisePropertyChanged("SorguKimlikNOTipi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SorguKimlikNO {
            get {
                return this.sorguKimlikNOField;
            }
            set {
                this.sorguKimlikNOField = value;
                this.RaisePropertyChanged("SorguKimlikNO");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public enum GIBFaalKodlari {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        Faal,
        
        /// <remarks/>
        Tanimsiz,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public enum GIBSirketTurleri {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        Gercek,
        
        /// <remarks/>
        Adi,
        
        /// <remarks/>
        Kollektif,
        
        /// <remarks/>
        AdiKomandit,
        
        /// <remarks/>
        ESHKomandit,
        
        /// <remarks/>
        LTD,
        
        /// <remarks/>
        Anonim,
        
        /// <remarks/>
        Koop,
        
        /// <remarks/>
        Diger,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
    public enum KimlikNOTipi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        TCKN,
        
        /// <remarks/>
        VKN,
        
        /// <remarks/>
        MTKN,
        
        /// <remarks/>
        TCSN,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TuzelSahisMukellefMerkezBilgiSorgu", WrapperNamespace="http://gbs.nps.tnb.org.tr/", IsWrapped=true)]
    public partial class TuzelSahisMukellefMerkezBilgiSorguRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbs.nps.tnb.org.tr/", Order=0)]
        public string vkn;
        
        public TuzelSahisMukellefMerkezBilgiSorguRequest() {
        }
        
        public TuzelSahisMukellefMerkezBilgiSorguRequest(TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader, TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader, string vkn) {
            this.BilgiServisHeader = BilgiServisHeader;
            this.NoterlikKimlikHeader = NoterlikKimlikHeader;
            this.vkn = vkn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TuzelSahisMukellefMerkezBilgiSorguResponse", WrapperNamespace="http://gbs.nps.tnb.org.tr/", IsWrapped=true)]
    public partial class TuzelSahisMukellefMerkezBilgiSorguResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.ServisHataHeader ServisHataHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbs.nps.tnb.org.tr/", Order=0)]
        public TacminMusavir.GIBBilgiServisi.MerkezBilgiSorguSonuc TuzelSahisMukellefMerkezBilgiSorguResult;
        
        public TuzelSahisMukellefMerkezBilgiSorguResponse() {
        }
        
        public TuzelSahisMukellefMerkezBilgiSorguResponse(TacminMusavir.GIBBilgiServisi.ServisHataHeader ServisHataHeader, TacminMusavir.GIBBilgiServisi.MerkezBilgiSorguSonuc TuzelSahisMukellefMerkezBilgiSorguResult) {
            this.ServisHataHeader = ServisHataHeader;
            this.TuzelSahisMukellefMerkezBilgiSorguResult = TuzelSahisMukellefMerkezBilgiSorguResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GercekSahisMukellefMerkezBilgiSorgu", WrapperNamespace="http://gbs.nps.tnb.org.tr/", IsWrapped=true)]
    public partial class GercekSahisMukellefMerkezBilgiSorguRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbs.nps.tnb.org.tr/", Order=0)]
        public long tckn;
        
        public GercekSahisMukellefMerkezBilgiSorguRequest() {
        }
        
        public GercekSahisMukellefMerkezBilgiSorguRequest(TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader, TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader, long tckn) {
            this.BilgiServisHeader = BilgiServisHeader;
            this.NoterlikKimlikHeader = NoterlikKimlikHeader;
            this.tckn = tckn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GercekSahisMukellefMerkezBilgiSorguResponse", WrapperNamespace="http://gbs.nps.tnb.org.tr/", IsWrapped=true)]
    public partial class GercekSahisMukellefMerkezBilgiSorguResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.ServisHataHeader ServisHataHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbs.nps.tnb.org.tr/", Order=0)]
        public TacminMusavir.GIBBilgiServisi.MerkezBilgiSorguSonuc GercekSahisMukellefMerkezBilgiSorguResult;
        
        public GercekSahisMukellefMerkezBilgiSorguResponse() {
        }
        
        public GercekSahisMukellefMerkezBilgiSorguResponse(TacminMusavir.GIBBilgiServisi.ServisHataHeader ServisHataHeader, TacminMusavir.GIBBilgiServisi.MerkezBilgiSorguSonuc GercekSahisMukellefMerkezBilgiSorguResult) {
            this.ServisHataHeader = ServisHataHeader;
            this.GercekSahisMukellefMerkezBilgiSorguResult = GercekSahisMukellefMerkezBilgiSorguResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaglantiTesti", WrapperNamespace="http://gbs.nps.tnb.org.tr/", IsWrapped=true)]
    public partial class BaglantiTestiRequest {
        
        public BaglantiTestiRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaglantiTestiResponse", WrapperNamespace="http://gbs.nps.tnb.org.tr/", IsWrapped=true)]
    public partial class BaglantiTestiResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://gbs.nps.tnb.org.tr/")]
        public TacminMusavir.GIBBilgiServisi.ServisHataHeader ServisHataHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbs.nps.tnb.org.tr/", Order=0)]
        public System.DateTime BaglantiTestiResult;
        
        public BaglantiTestiResponse() {
        }
        
        public BaglantiTestiResponse(TacminMusavir.GIBBilgiServisi.ServisHataHeader ServisHataHeader, System.DateTime BaglantiTestiResult) {
            this.ServisHataHeader = ServisHataHeader;
            this.BaglantiTestiResult = BaglantiTestiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GIBBilgiServisiSoapChannel : TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GIBBilgiServisiSoapClient : System.ServiceModel.ClientBase<TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap>, TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap {
        
        public GIBBilgiServisiSoapClient() {
        }
        
        public GIBBilgiServisiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GIBBilgiServisiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GIBBilgiServisiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GIBBilgiServisiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguResponse TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap.TuzelSahisMukellefMerkezBilgiSorgu(TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest request) {
            return base.Channel.TuzelSahisMukellefMerkezBilgiSorgu(request);
        }
        
        public TacminMusavir.GIBBilgiServisi.ServisHataHeader TuzelSahisMukellefMerkezBilgiSorgu(TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader, TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader, string vkn, out TacminMusavir.GIBBilgiServisi.MerkezBilgiSorguSonuc TuzelSahisMukellefMerkezBilgiSorguResult) {
            TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest inValue = new TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest();
            inValue.BilgiServisHeader = BilgiServisHeader;
            inValue.NoterlikKimlikHeader = NoterlikKimlikHeader;
            inValue.vkn = vkn;
            TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguResponse retVal = ((TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap)(this)).TuzelSahisMukellefMerkezBilgiSorgu(inValue);
            TuzelSahisMukellefMerkezBilgiSorguResult = retVal.TuzelSahisMukellefMerkezBilgiSorguResult;
            return retVal.ServisHataHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguResponse> TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap.TuzelSahisMukellefMerkezBilgiSorguAsync(TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest request) {
            return base.Channel.TuzelSahisMukellefMerkezBilgiSorguAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguResponse> TuzelSahisMukellefMerkezBilgiSorguAsync(TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader, TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader, string vkn) {
            TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest inValue = new TacminMusavir.GIBBilgiServisi.TuzelSahisMukellefMerkezBilgiSorguRequest();
            inValue.BilgiServisHeader = BilgiServisHeader;
            inValue.NoterlikKimlikHeader = NoterlikKimlikHeader;
            inValue.vkn = vkn;
            return ((TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap)(this)).TuzelSahisMukellefMerkezBilgiSorguAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguResponse TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap.GercekSahisMukellefMerkezBilgiSorgu(TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest request) {
            return base.Channel.GercekSahisMukellefMerkezBilgiSorgu(request);
        }
        
        public TacminMusavir.GIBBilgiServisi.ServisHataHeader GercekSahisMukellefMerkezBilgiSorgu(TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader, TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader, long tckn, out TacminMusavir.GIBBilgiServisi.MerkezBilgiSorguSonuc GercekSahisMukellefMerkezBilgiSorguResult) {
            TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest inValue = new TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest();
            inValue.BilgiServisHeader = BilgiServisHeader;
            inValue.NoterlikKimlikHeader = NoterlikKimlikHeader;
            inValue.tckn = tckn;
            TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguResponse retVal = ((TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap)(this)).GercekSahisMukellefMerkezBilgiSorgu(inValue);
            GercekSahisMukellefMerkezBilgiSorguResult = retVal.GercekSahisMukellefMerkezBilgiSorguResult;
            return retVal.ServisHataHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguResponse> TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap.GercekSahisMukellefMerkezBilgiSorguAsync(TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest request) {
            return base.Channel.GercekSahisMukellefMerkezBilgiSorguAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguResponse> GercekSahisMukellefMerkezBilgiSorguAsync(TacminMusavir.GIBBilgiServisi.BilgiServisHeader BilgiServisHeader, TacminMusavir.GIBBilgiServisi.NoterlikKimlikHeader NoterlikKimlikHeader, long tckn) {
            TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest inValue = new TacminMusavir.GIBBilgiServisi.GercekSahisMukellefMerkezBilgiSorguRequest();
            inValue.BilgiServisHeader = BilgiServisHeader;
            inValue.NoterlikKimlikHeader = NoterlikKimlikHeader;
            inValue.tckn = tckn;
            return ((TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap)(this)).GercekSahisMukellefMerkezBilgiSorguAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TacminMusavir.GIBBilgiServisi.BaglantiTestiResponse TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap.BaglantiTesti(TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest request) {
            return base.Channel.BaglantiTesti(request);
        }
        
        public TacminMusavir.GIBBilgiServisi.ServisHataHeader BaglantiTesti(out System.DateTime BaglantiTestiResult) {
            TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest inValue = new TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest();
            TacminMusavir.GIBBilgiServisi.BaglantiTestiResponse retVal = ((TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap)(this)).BaglantiTesti(inValue);
            BaglantiTestiResult = retVal.BaglantiTestiResult;
            return retVal.ServisHataHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.BaglantiTestiResponse> TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap.BaglantiTestiAsync(TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest request) {
            return base.Channel.BaglantiTestiAsync(request);
        }
        
        public System.Threading.Tasks.Task<TacminMusavir.GIBBilgiServisi.BaglantiTestiResponse> BaglantiTestiAsync() {
            TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest inValue = new TacminMusavir.GIBBilgiServisi.BaglantiTestiRequest();
            return ((TacminMusavir.GIBBilgiServisi.GIBBilgiServisiSoap)(this)).BaglantiTestiAsync(inValue);
        }
    }
}
