#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tacmin.Core.Extensions;
    using Tacmin.Core.Model;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Errors/Http404.cshtml")]
    public partial class _Views_Errors_Http404_cshtml : Tacmin.Core.Infrastructure.WebViewPageBase<ErrorViewModel>
    {
        public _Views_Errors_Http404_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"error-page\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"headline text-warning\"");

WriteLiteral("> 404</h2>\r\n\r\n    <div");

WriteLiteral(" class=\"error-content\"");

WriteLiteral(">\r\n        <h3><i");

WriteLiteral(" class=\"fas fa-exclamation-triangle text-warning\"");

WriteLiteral("></i> Oops! Sayfa Bulunamdı.</h3>\r\n\r\n        <p>\r\n            Sunucularımızda bu " +
"sayfanın adresini bulamadık.\r\n            Adres değiştirilmiş veya tamamen kaldı" +
"rılmış olabilir.\r\n            Bir şeylerin ters gittiğini düşünüyorsanız\r\n      " +
"      <a");

WriteLiteral(" href=\"https://tacminyazilim.com/iletisim\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">İletişim</a> sayfamızdan bize ulaşabilirsiniz.\r\n        </p>\r\n\r\n");

            
            #line 16 "..\..\Views\Errors\Http404.cshtml"
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Errors\Http404.cshtml"
         if (Model.ErrorMessages != null && Model.ErrorMessages.Any())
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>\r\n                <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" href=\"#collapseExample\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"collapseExample\"");

WriteLiteral(">\r\n                    Hata Detayı\r\n                </a>\r\n            </p>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" id=\"collapseExample\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"card card-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Errors\Http404.cshtml"
               Write(Model.ErrorMessages.Join("<br />"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

            
            #line 28 "..\..\Views\Errors\Http404.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
