#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tacmin.Core.Extensions;
    using Tacmin.Core.Model;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Errors/Http500.cshtml")]
    public partial class _Views_Errors_Http500_cshtml : Tacmin.Core.Infrastructure.WebViewPageBase<ErrorViewModel>
    {
        public _Views_Errors_Http500_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"error-page\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"headline text-danger\"");

WriteLiteral(">500</h2>\r\n\r\n    <div");

WriteLiteral(" class=\"error-content\"");

WriteLiteral(">\r\n        <h3><i");

WriteLiteral(" class=\"fas fa-exclamation-triangle text-danger\"");

WriteLiteral("></i> Oops! Birşeyler yanlış gitti.</h3>\r\n\r\n        <p>\r\n            Yaşadığınız " +
"problem yazılım ekibimize iletildi.\r\n            Mümkün olan en kısa sürede çözü" +
"m üretmek için çalışacağız.\r\n        </p>\r\n\r\n        <p>\r\n            <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" href=\"#collapseExample\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"collapseExample\"");

WriteLiteral(">\r\n                Hata Detayı\r\n            </a>\r\n        </p>\r\n        <div");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" id=\"collapseExample\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Errors\Http500.cshtml"
           Write(Model.ErrorMessages.Join("<br />"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
